### PR TITLE
fix(blob): Makes sure `SizedStream` impls `Stream`

### LINKED ISSUE #157: v0.12.0: `pull_blob_stream` result does not implement `Stream`
The return type changed from `impl Stream` to `SizedStream`, which does not implement `Stream`.

Works in v0.11.0:

```diff
diff --git a/src/client.rs b/src/client.rs
index d2a0646..3b4d710 100644
--- a/src/client.rs
+++ b/src/client.rs
@@ -1006,6 +1006,27 @@ impl Client {
     ///
     /// This is a streaming version of [`Client::pull_blob`].
     /// Returns [`Stream`](futures_util::Stream).
+    ///
+    /// ```
+    /// use oci_distribution::{Client, Reference};
+    /// use oci_distribution::client::ClientConfig;
+    /// use oci_distribution::manifest::OciDescriptor;
+    /// use std::future::Future;
+    /// use std::io::Error;
+    /// 
+    /// struct StreamHandler<S: futures_util::Stream<Item = std::result::Result<bytes::Bytes, std::io::Error>>>{
+    ///   stream: S
+    /// };
+    /// 
+    /// async {
+    ///   let config = ClientConfig { ..Default::default() };
+    ///   let client = Client::new(config);
+    ///   let imgRef: Reference = "busybox:latest".parse().unwrap();
+    ///   let desc = OciDescriptor { digest: "sha256:deadbeef".to_owned(), ..Default::default() };
+    ///   let stream = client.pull_blob_stream(&imgRef, &desc).await.unwrap();
+    ///   StreamHandler{stream};
+    /// };
+    /// ```
     pub async fn pull_blob_stream(
         &self,
         image: &Reference,
```

Fails in v0.12.0 with `the trait Stream is not implemented for SizedStream`

```diff
diff --git a/src/client.rs b/src/client.rs
index 119c3e0..c4785f5 100644
--- a/src/client.rs
+++ b/src/client.rs
@@ -1091,6 +1091,27 @@ impl Client {
     ///
     /// This is a streaming version of [`Client::pull_blob`].
     /// Returns [`Stream`](futures_util::Stream).
+    ///
+    /// ```
+    /// use oci_client::{Client, Reference};
+    /// use oci_client::client::ClientConfig;
+    /// use oci_client::manifest::OciDescriptor;
+    /// use std::future::Future;
+    /// use std::io::Error;
+    /// 
+    /// struct StreamHandler<S: futures_util::Stream<Item = std::result::Result<bytes::Bytes, std::io::Error>>>{
+    ///   stream: S
+    /// };
+    /// 
+    /// async {
+    ///   let config = ClientConfig { ..Default::default() };
+    ///   let client = Client::new(config);
+    ///   let imgRef: Reference = "busybox:latest".parse().unwrap();
+    ///   let desc = OciDescriptor { digest: "sha256:deadbeef".to_owned(), ..Default::default() };
+    ///   let stream = client.pull_blob_stream(&imgRef, &desc).await.unwrap();
+    ///   StreamHandler{stream};
+    /// };
+    /// ```
     pub async fn pull_blob_stream(
         &self,
         image: &Reference,
```

### PR DESCRIPTION
**Pull request by thomastaylor312**
This impls a simple passthrough stream implementation for `SizedStream`. It also updates the doc to show how you can use the stream directly. Please note that although this is _technically_ an add by adding the impl Stream, it really just fixes some possibly annoying ergonomics. So I marked this as 0.12.1

Fixes #157

### CODE REVIEW

**Review by flavio — APPROVED** [review]
I totally fine with both the change and the decision to make it a patch release
