### ISSUE TITLE
v0.12.0: `pull_blob_stream` result does not implement `Stream`

### ISSUE THREAD

**Issue by burgerdev** [oras-project/rust-oci-client#157]
The return type changed from `impl Stream` to `SizedStream`, which does not implement `Stream`.

Works in v0.11.0:

```diff
diff --git a/src/client.rs b/src/client.rs
index d2a0646..3b4d710 100644
--- a/src/client.rs
+++ b/src/client.rs
@@ -1006,6 +1006,27 @@ impl Client {
     ///
     /// This is a streaming version of [`Client::pull_blob`].
     /// Returns [`Stream`](futures_util::Stream).
+    ///
+    /// ```
+    /// use oci_distribution::{Client, Reference};
+    /// use oci_distribution::client::ClientConfig;
+    /// use oci_distribution::manifest::OciDescriptor;
+    /// use std::future::Future;
+    /// use std::io::Error;
+    /// 
+    /// struct StreamHandler<S: futures_util::Stream<Item = std::result::Result<bytes::Bytes, std::io::Error>>>{
+    ///   stream: S
+    /// };
+    /// 
+    /// async {
+    ///   let config = ClientConfig { ..Default::default() };
+    ///   let client = Client::new(config);
+    ///   let imgRef: Reference = "busybox:latest".parse().unwrap();
+    ///   let desc = OciDescriptor { digest: "sha256:deadbeef".to_owned(), ..Default::default() };
+    ///   let stream = client.pull_blob_stream(&imgRef, &desc).await.unwrap();
+    ///   StreamHandler{stream};
+    /// };
+    /// ```
     pub async fn pull_blob_stream(
         &self,
         image: &Reference,
```

Fails in v0.12.0 with `the trait Stream is not implemented for SizedStream`

```diff
diff --git a/src/client.rs b/src/client.rs
index 119c3e0..c4785f5 100644
--- a/src/client.rs
+++ b/src/client.rs
@@ -1091,6 +1091,27 @@ impl Client {
     ///
     /// This is a streaming version of [`Client::pull_blob`].
     /// Returns [`Stream`](futures_util::Stream).
+    ///
+    /// ```
+    /// use oci_client::{Client, Reference};
+    /// use oci_client::client::ClientConfig;
+    /// use oci_client::manifest::OciDescriptor;
+    /// use std::future::Future;
+    /// use std::io::Error;
+    /// 
+    /// struct StreamHandler<S: futures_util::Stream<Item = std::result::Result<bytes::Bytes, std::io::Error>>>{
+    ///   stream: S
+    /// };
+    /// 
+    /// async {
+    ///   let config = ClientConfig { ..Default::default() };
+    ///   let client = Client::new(config);
+    ///   let imgRef: Reference = "busybox:latest".parse().unwrap();
+    ///   let desc = OciDescriptor { digest: "sha256:deadbeef".to_owned(), ..Default::default() };
+    ///   let stream = client.pull_blob_stream(&imgRef, &desc).await.unwrap();
+    ///   StreamHandler{stream};
+    /// };
+    /// ```
     pub async fn pull_blob_stream(
         &self,
         image: &Reference,
```

**Comment by burgerdev** [comment]
I just realized that the `SizedStream.stream` field is public, which then only means that the docstring needs to be adjusted.

**Comment by thomastaylor312** [comment]
Ah yep I must have missed that in review. I thought about requiring it to impl Stream, but felt like overkill at the time. I can update doc string and maybe I'll just implement stream on it while I'm there 😆
